name: API Deployment

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:
  build:
    name: Building Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publishing container
        run: |
          echo "${{secrets.BEPIZU_DRAFT_KEY}}" > ./server-key.pem
          chmod 400 ./server-key.pem
          eval $(ssh-agent)
          ssh-add -k ./server-key.pem
          mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config

          export DOCKER_HOST="ssh://ubuntu@api.bepizu.com.br"

          echo "PORT=8001" >> .env
          echo "MONGODB_URI=mongodb://localhost:27017" >> .env

          npm i

          docker image build -t bepizu-api:latest -f Dockerfile .

          docker container stop bepizu-api || echo "bepizu-api's container not running"
          docker run -d --name bepizu-api --restart unless-stopped --network host bepizu-api:latest

          docker system prune -a -f
